extends Node

# warning-ignore:unused_signal
signal splash_screen_end
# warning-ignore:unused_signal
signal start_game_pressed
# warning-ignore:unused_signal
signal view_credits_pressed
# warning-ignore:unused_signal
signal quit_game_pressed
# warning-ignore:unused_signal
signal continue_game_pressed
# warning-ignore:unused_signal
signal quit_level_pressed
# warning-ignore:unused_signal
signal game_menu_opened
# warning-ignore:unused_signal
signal game_menu_closed
# warning-ignore:unused_signal
signal credit_screen_end
# warning-ignore:unused_signal
signal entered_water_surface
# warning-ignore:unused_signal
signal exited_water_surface
# warning-ignore:unused_signal
signal entered_water
# warning-ignore:unused_signal
signal exited_water
# warning-ignore:unused_signal
signal entered_under_water
# warning-ignore:unused_signal
signal exited_under_water
